
include <openscad-new-dimensions/constants.scad>;
ROOF_RENDER_GAP_FLAT = 20;
ROOF_RENDER_MODE_3D = DIMENSION_RENDER_MODE_3D;
ROOF_RENDER_MODE_FLAT = "Flat";
ROOF_RENDER_MODE_2D = DIMENSION_RENDER_MODE_2D;
ROOF_RENDER_MODE = ROOF_RENDER_MODE_3D;